/*
 * Fiverr
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.30
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from "../ApiClient";

/**
* CongViec service.
* @module api/CongViecApi
* @version v1
*/
export class CongViecApi {

    /**
    * Constructs a new CongViecApi. 
    * @alias module:api/CongViecApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * @param {Number} id 
     * @param {String} tokenCybersoft Nhập token cybersoft
     * @param {Object} opts Optional parameters
     * @param {String} opts.token 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    callDeleteWithHttpInfo(id, tokenCybersoft, opts) {
      opts = opts || {};
      let postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling callDelete");
      }

      // verify the required parameter 'tokenCybersoft' is set
      if (tokenCybersoft === undefined || tokenCybersoft === null) {
        throw new Error("Missing the required parameter 'tokenCybersoft' when calling callDelete");
      }


      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
        'token': opts['token'],
        'tokenCybersoft': tokenCybersoft
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/api/cong-viec/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * @param {Number} id 
     * @param {String} tokenCybersoft Nhập token cybersoft
     * @param {Object} opts Optional parameters
     * @param {String} opts.token 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    callDelete(id, tokenCybersoft, opts) {
      return this.callDeleteWithHttpInfo(id, tokenCybersoft, opts)
        .then(function(response_and_data) {
          return response_and_data.response.body;
        });
    }


    /**
     * @param {String} tokenCybersoft Nhập token cybersoft
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    getWithHttpInfo(tokenCybersoft, token) {
      let postBody = null;

      // verify the required parameter 'tokenCybersoft' is set
      if (tokenCybersoft === undefined || tokenCybersoft === null) {
        throw new Error("Missing the required parameter 'tokenCybersoft' when calling get");
      }


      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'tokenCybersoft': tokenCybersoft,
        'token': token
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/api/cong-viec', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * @param {String} tokenCybersoft Nhập token cybersoft
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    get(tokenCybersoft, token) {
      return this.getWithHttpInfo(tokenCybersoft, token)
        .then(function(response_and_data) {
          return response_and_data.response.body;
        });
    }


    /**
     * @param {Number} maLoaiCongViec 
     * @param {String} tokenCybersoft Nhập token cybersoft
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    getChiTietLoaiCongViecWithHttpInfo(maLoaiCongViec, tokenCybersoft) {
      let postBody = null;

      // verify the required parameter 'maLoaiCongViec' is set
      if (maLoaiCongViec === undefined || maLoaiCongViec === null) {
        throw new Error("Missing the required parameter 'maLoaiCongViec' when calling getChiTietLoaiCongViec");
      }

      // verify the required parameter 'tokenCybersoft' is set
      if (tokenCybersoft === undefined || tokenCybersoft === null) {
        throw new Error("Missing the required parameter 'tokenCybersoft' when calling getChiTietLoaiCongViec");
      }


      let pathParams = {
        'MaLoaiCongViec': maLoaiCongViec
      };
      let queryParams = {
      };
      let headerParams = {
        'tokenCybersoft': tokenCybersoft
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/api/cong-viec/lay-chi-tiet-loai-cong-viec/{MaLoaiCongViec}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * @param {Number} maLoaiCongViec 
     * @param {String} tokenCybersoft Nhập token cybersoft
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    getChiTietLoaiCongViec(maLoaiCongViec, tokenCybersoft) {
      return this.getChiTietLoaiCongViecWithHttpInfo(maLoaiCongViec, tokenCybersoft)
        .then(function(response_and_data) {
          return response_and_data.response.body;
        });
    }


    /**
     * @param {Number} maCongViec 
     * @param {String} tokenCybersoft Nhập token cybersoft
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    getCongViecChiTietWithHttpInfo(maCongViec, tokenCybersoft) {
      let postBody = null;

      // verify the required parameter 'maCongViec' is set
      if (maCongViec === undefined || maCongViec === null) {
        throw new Error("Missing the required parameter 'maCongViec' when calling getCongViecChiTiet");
      }

      // verify the required parameter 'tokenCybersoft' is set
      if (tokenCybersoft === undefined || tokenCybersoft === null) {
        throw new Error("Missing the required parameter 'tokenCybersoft' when calling getCongViecChiTiet");
      }


      let pathParams = {
        'MaCongViec': maCongViec
      };
      let queryParams = {
      };
      let headerParams = {
        'tokenCybersoft': tokenCybersoft
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/api/cong-viec/lay-cong-viec-chi-tiet/{MaCongViec}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * @param {Number} maCongViec 
     * @param {String} tokenCybersoft Nhập token cybersoft
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    getCongViecChiTiet(maCongViec, tokenCybersoft) {
      return this.getCongViecChiTietWithHttpInfo(maCongViec, tokenCybersoft)
        .then(function(response_and_data) {
          return response_and_data.response.body;
        });
    }


    /**
     * @param {Number} maChiTietLoai 
     * @param {String} tokenCybersoft Nhập token cybersoft
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    getCongViecTheoChiTietLoaiWithHttpInfo(maChiTietLoai, tokenCybersoft) {
      let postBody = null;

      // verify the required parameter 'maChiTietLoai' is set
      if (maChiTietLoai === undefined || maChiTietLoai === null) {
        throw new Error("Missing the required parameter 'maChiTietLoai' when calling getCongViecTheoChiTietLoai");
      }

      // verify the required parameter 'tokenCybersoft' is set
      if (tokenCybersoft === undefined || tokenCybersoft === null) {
        throw new Error("Missing the required parameter 'tokenCybersoft' when calling getCongViecTheoChiTietLoai");
      }


      let pathParams = {
        'MaChiTietLoai': maChiTietLoai
      };
      let queryParams = {
      };
      let headerParams = {
        'tokenCybersoft': tokenCybersoft
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/api/cong-viec/lay-cong-viec-theo-chi-tiet-loai/{MaChiTietLoai}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * @param {Number} maChiTietLoai 
     * @param {String} tokenCybersoft Nhập token cybersoft
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    getCongViecTheoChiTietLoai(maChiTietLoai, tokenCybersoft) {
      return this.getCongViecTheoChiTietLoaiWithHttpInfo(maChiTietLoai, tokenCybersoft)
        .then(function(response_and_data) {
          return response_and_data.response.body;
        });
    }


    /**
     * @param {String} tenCongViec 
     * @param {String} tokenCybersoft Nhập token cybersoft
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    getCongViecTheoTenWithHttpInfo(tenCongViec, tokenCybersoft) {
      let postBody = null;

      // verify the required parameter 'tenCongViec' is set
      if (tenCongViec === undefined || tenCongViec === null) {
        throw new Error("Missing the required parameter 'tenCongViec' when calling getCongViecTheoTen");
      }

      // verify the required parameter 'tokenCybersoft' is set
      if (tokenCybersoft === undefined || tokenCybersoft === null) {
        throw new Error("Missing the required parameter 'tokenCybersoft' when calling getCongViecTheoTen");
      }


      let pathParams = {
        'TenCongViec': tenCongViec
      };
      let queryParams = {
      };
      let headerParams = {
        'tokenCybersoft': tokenCybersoft
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/api/cong-viec/lay-danh-sach-cong-viec-theo-ten/{TenCongViec}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * @param {String} tenCongViec 
     * @param {String} tokenCybersoft Nhập token cybersoft
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    getCongViecTheoTen(tenCongViec, tokenCybersoft) {
      return this.getCongViecTheoTenWithHttpInfo(tenCongViec, tokenCybersoft)
        .then(function(response_and_data) {
          return response_and_data.response.body;
        });
    }


    /**
     * @param {String} tokenCybersoft Nhập token cybersoft
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    getMenuLoaiCongViecWithHttpInfo(tokenCybersoft) {
      let postBody = null;

      // verify the required parameter 'tokenCybersoft' is set
      if (tokenCybersoft === undefined || tokenCybersoft === null) {
        throw new Error("Missing the required parameter 'tokenCybersoft' when calling getMenuLoaiCongViec");
      }


      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'tokenCybersoft': tokenCybersoft
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/api/cong-viec/lay-menu-loai-cong-viec', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * @param {String} tokenCybersoft Nhập token cybersoft
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    getMenuLoaiCongViec(tokenCybersoft) {
      return this.getMenuLoaiCongViecWithHttpInfo(tokenCybersoft)
        .then(function(response_and_data) {
          return response_and_data.response.body;
        });
    }


    /**
     * @param {String} tokenCybersoft Nhập token cybersoft
     * @param {Object} opts Optional parameters
     * @param {Number} opts.pageIndex 
     * @param {Number} opts.pageSize 
     * @param {String} opts.keyword 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    getPagingWithHttpInfo(tokenCybersoft, opts) {
      opts = opts || {};
      let postBody = null;

      // verify the required parameter 'tokenCybersoft' is set
      if (tokenCybersoft === undefined || tokenCybersoft === null) {
        throw new Error("Missing the required parameter 'tokenCybersoft' when calling getPaging");
      }


      let pathParams = {
      };
      let queryParams = {
        'pageIndex': opts['pageIndex'],
        'pageSize': opts['pageSize'],
        'keyword': opts['keyword']
      };
      let headerParams = {
        'tokenCybersoft': tokenCybersoft
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/api/cong-viec/phan-trang-tim-kiem', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * @param {String} tokenCybersoft Nhập token cybersoft
     * @param {Object} opts Optional parameters
     * @param {Number} opts.pageIndex 
     * @param {Number} opts.pageSize 
     * @param {String} opts.keyword 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    getPaging(tokenCybersoft, opts) {
      return this.getPagingWithHttpInfo(tokenCybersoft, opts)
        .then(function(response_and_data) {
          return response_and_data.response.body;
        });
    }


    /**
     * @param {Number} id 
     * @param {String} tokenCybersoft Nhập token cybersoft
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    get_0WithHttpInfo(id, tokenCybersoft) {
      let postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling get_0");
      }

      // verify the required parameter 'tokenCybersoft' is set
      if (tokenCybersoft === undefined || tokenCybersoft === null) {
        throw new Error("Missing the required parameter 'tokenCybersoft' when calling get_0");
      }


      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
        'tokenCybersoft': tokenCybersoft
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/api/cong-viec/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * @param {Number} id 
     * @param {String} tokenCybersoft Nhập token cybersoft
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    get_0(id, tokenCybersoft) {
      return this.get_0WithHttpInfo(id, tokenCybersoft)
        .then(function(response_and_data) {
          return response_and_data.response.body;
        });
    }


    /**
     * @param {String} tokenCybersoft Nhập token cybersoft
     * @param {Object} opts Optional parameters
     * @param {String} opts.token 
     * @param {module:model/CongViecViewModel} opts.model 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    postWithHttpInfo(tokenCybersoft, opts) {
      opts = opts || {};
      let postBody = opts['model'];

      // verify the required parameter 'tokenCybersoft' is set
      if (tokenCybersoft === undefined || tokenCybersoft === null) {
        throw new Error("Missing the required parameter 'tokenCybersoft' when calling post");
      }


      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'token': opts['token'],
        'tokenCybersoft': tokenCybersoft
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json-patch+json', 'application/json', 'text/json', 'application/_*+json'];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/api/cong-viec', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * @param {String} tokenCybersoft Nhập token cybersoft
     * @param {Object} opts Optional parameters
     * @param {String} opts.token 
     * @param {module:model/CongViecViewModel} opts.model 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    post(tokenCybersoft, opts) {
      return this.postWithHttpInfo(tokenCybersoft, opts)
        .then(function(response_and_data) {
          return response_and_data.response.body;
        });
    }


    /**
     * @param {Number} id 
     * @param {String} tokenCybersoft Nhập token cybersoft
     * @param {Object} opts Optional parameters
     * @param {String} opts.token 
     * @param {module:model/CongViecViewModel} opts.model 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    putWithHttpInfo(id, tokenCybersoft, opts) {
      opts = opts || {};
      let postBody = opts['model'];

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling put");
      }

      // verify the required parameter 'tokenCybersoft' is set
      if (tokenCybersoft === undefined || tokenCybersoft === null) {
        throw new Error("Missing the required parameter 'tokenCybersoft' when calling put");
      }


      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
        'token': opts['token'],
        'tokenCybersoft': tokenCybersoft
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json-patch+json', 'application/json', 'text/json', 'application/_*+json'];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/api/cong-viec/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * @param {Number} id 
     * @param {String} tokenCybersoft Nhập token cybersoft
     * @param {Object} opts Optional parameters
     * @param {String} opts.token 
     * @param {module:model/CongViecViewModel} opts.model 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    put(id, tokenCybersoft, opts) {
      return this.putWithHttpInfo(id, tokenCybersoft, opts)
        .then(function(response_and_data) {
          return response_and_data.response.body;
        });
    }


    /**
     * @param {Number} maCongViec 
     * @param {String} tokenCybersoft Nhập token cybersoft
     * @param {Object} opts Optional parameters
     * @param {String} opts.token 
     * @param {File} opts.formFile 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    uploadHinhNhomLoaiWithHttpInfo(maCongViec, tokenCybersoft, opts) {
      opts = opts || {};
      let postBody = null;

      // verify the required parameter 'maCongViec' is set
      if (maCongViec === undefined || maCongViec === null) {
        throw new Error("Missing the required parameter 'maCongViec' when calling uploadHinhNhomLoai");
      }

      // verify the required parameter 'tokenCybersoft' is set
      if (tokenCybersoft === undefined || tokenCybersoft === null) {
        throw new Error("Missing the required parameter 'tokenCybersoft' when calling uploadHinhNhomLoai");
      }


      let pathParams = {
        'MaCongViec': maCongViec
      };
      let queryParams = {
      };
      let headerParams = {
        'token': opts['token'],
        'tokenCybersoft': tokenCybersoft
      };
      let formParams = {
        'formFile': opts['formFile']
      };

      let authNames = [];
      let contentTypes = ['multipart/form-data'];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/api/cong-viec/upload-hinh-cong-viec/{MaCongViec}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * @param {Number} maCongViec 
     * @param {String} tokenCybersoft Nhập token cybersoft
     * @param {Object} opts Optional parameters
     * @param {String} opts.token 
     * @param {File} opts.formFile 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    uploadHinhNhomLoai(maCongViec, tokenCybersoft, opts) {
      return this.uploadHinhNhomLoaiWithHttpInfo(maCongViec, tokenCybersoft, opts)
        .then(function(response_and_data) {
          return response_and_data.response.body;
        });
    }


}
